software:
  version: 0.0.1v
  app_name: RecombTracer
  author: RecombTracer Team
  email: zhangjian199567@outlook.com
  url: https://github.com/xsx123123/RecombTrac
  description: Recombination breakpoint detection for multi-parental populations
