software:
  version: 0.0.1
  app_name: RecombTracer
  author: RecombTracer Team
  email: zhangjian199567@outlook.com
  url: https://github.com/xsx123123/RecombTracer
  description: Recombination breakpoint detection in synthetic multi-parental populations
